### ISSUE TITLE
tfsec against tf code using terraform-aws-modules/s3-bucket/aws fails 2 checks

### ISSUE THREAD

**Issue by dhallam** [aquasecurity/tfsec#1010]
**Describe the bug**
When trying to apply tfsec to terraform code that uses `terraform-aws-modules/s3-bucket/aws`, I can't seem to make it pass the `aws-s3-enable-bucket-encryption` and `aws-s3-specify-public-access-block` checks.  I believe that I have configured the module in such a way that it should pass the checks. 

**To Reproduce**
```
$ terraform --version
Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.53.0
```

```
$ tfsec --version
0.57.1
```

Create file `main.tf`:
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  region = "eu-west-2"
}

resource "aws_kms_key" "objects" {
  description             = "KMS key is used to encrypt bucket objects"
  deletion_window_in_days = 7
  enable_key_rotation     = true
}

module "s3_bucket" {
  source = "terraform-aws-modules/s3-bucket/aws"

  bucket = "my-s3-bucket"
  acl    = "private"

  attach_public_policy    = true
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true

  logging = {
    target_bucket = "my-log-bucket"
    target_prefix = "log/"
  }

  server_side_encryption_configuration = {
    rule = {
      apply_server_side_encryption_by_default = {
        kms_master_key_id = aws_kms_key.objects.arn
        sse_algorithm     = "aws:kms"
      }
    }
  }

  versioning = {
    enabled = true
  }
}
```

Run
```
$ terraform init
$ tfsec .
```

**Expected behavior**
Checks should pass

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04

**Additional context**
None

**Comment by liamg** [comment]
Hey @dhallam we have a fix for this that we're testing - we should have a release for you tomorrow :+1:

**Comment by liamg** [comment]
This should now work in `v0.58.0`.

**Comment by dhallam** [comment]
Hi @liamg . Many thanks for the update. The `aws-s3-enable-bucket-encryption` check now passes. :star: 

However, the `aws-s3-specify-public-access-block` check is still failing with the example that is attached to this Issue.  The `attach_public_policy` module variable is set to `true` so that will trigger the creation of 

```
resource "aws_s3_bucket_public_access_block" "this"
```

**Comment by liamg** [comment]
Hey @dhallam, apologies for that, I missed that both of those should pass in the original comment. The issue was that we weren't always looking for referenced blocks in the right module.

This fix is now merged and in `v0.58.2` which is building now. I've tested against your example and it passes a scan :+1:

**Comment by dhallam** [comment]
Many thanks @liamg - that's all working. Thank you for your speedy response.
