### ISSUE TITLE
bug: non-deterministic behavior/results due to for_each processing for v1+ releases

### ISSUE THREAD

**Issue by BryanStenson-okta** [aquasecurity/tfsec#1495]
**Describe the bug**
Some combination of tf resources yields inconsistent results.

**To Reproduce**
1. Create directory the files from this gist: https://gist.github.com/BryanStenson-okta/caf244cc5ffbf25a590f4a3fc5d7ae51
2. Run `tfsec .` repeatedly (sometimes at least 10-20 times), and observe different results.

**Expected behavior**
Each execution of tfsec, on the identical codebase, should yield identical results.

**Screenshots/Output**

**System Info**

 - tfsec version: `v1.0.11`
 - terraform version: `v1.1.3`
 - OS: `osx`

**Example Code**

https://gist.github.com/BryanStenson-okta/caf244cc5ffbf25a590f4a3fc5d7ae51

**Additional context**

**Comment by BryanStenson-okta** [comment]
this seems to be related to `# tfsec:ignore` directives....removing them all from the codebase, i get a consistent result.

more details coming soon.

**Comment by BryanStenson-okta** [comment]
ok, more narrowing down.  i have a flat directory structure.  there are 0 subdirectories.  there are 0 uses of `tfsec:ignore` anywhere in the files in this structure.

repeated execution yields different outcome, specifically of the `"severity": "LOW"` variety:

```
% tfsec . -f json 2>/dev/null | jq -r '[.results | .[] | select(.severity == "LOW")] | length'
16
% tfsec . -f json 2>/dev/null | jq -r '[.results | .[] | select(.severity == "LOW")] | length'
22
% find . -type d
.
%
```

**Comment by BryanStenson-okta** [comment]
Some debug output:
```
...
[DEBUG][2022-02-03 16:43:45.950557 -0800 PST m=+136.528057162] Added aws_api_gateway_method.slack_post from for_each
[DEBUG][2022-02-03 16:43:45.950988 -0800 PST m=+136.528487588] Added aws_api_gateway_method.slack_post from for_each
[DEBUG][2022-02-03 16:43:45.951165 -0800 PST m=+136.528664347] Added aws_api_gateway_method.slack_post from for_each
[DEBUG][2022-02-03 16:43:45.951318 -0800 PST m=+136.528817260] Added aws_api_gateway_method.slack_post from for_each
[DEBUG][2022-02-03 16:43:45.951479 -0800 PST m=+136.528978549] Added aws_api_gateway_method.slack_post from for_each
...

```

aws_api_gateway_method.slack_post (https://gist.github.com/BryanStenson-okta/caf244cc5ffbf25a590f4a3fc5d7ae51#file-gistfile1-txt-L129) should only have 2 copies after expanding the for_each block.  It's for_each block points to aws_api_gateway_rest_api.main (https://gist.github.com/BryanStenson-okta/caf244cc5ffbf25a590f4a3fc5d7ae51#file-gistfile1-txt-L6-L7).  aws_api_gateway_rest_api.main for_each block points to local.api_gateway_endpoints (https://gist.github.com/BryanStenson-okta/caf244cc5ffbf25a590f4a3fc5d7ae51#file-gistfile1-txt-L194-L201) -- and there are only 2.

I don't yet have a fix, but I can see this problem happening intermittently.

**Comment by BryanStenson-okta** [comment]
the bug seems to appear only when resources reference each other when in different files.

if i combine the files from my gist into a single `all.tf` file, i get consistent results each time.

**Comment by BryanStenson-okta** [comment]
i've verified this all works as expected when running tfsec `v0.63.1`

**Comment by liamg** [comment]
Thanks for the report and extra info, looking into this today :+1:

**Comment by BryanStenson-okta** [comment]
I've verified `v1.1.1` works on the files I've provided in the gist.

However, I'm still seeing non-determinism on my codebase.  I'm sanitizing this to provide a reduced/cleaned example in another gist:

```
$ ~/Downloads/tfsec-darwin-amd64 --version
v1.1.1
$ ~/Downloads/tfsec-darwin-amd64 . -f json 2>/dev/null | jq -r '.results | length'
41
$ ~/Downloads/tfsec-darwin-amd64 . -f json 2>/dev/null | jq -r '.results | length'
40
$ ~/Downloads/tfsec-darwin-amd64 . -f json 2>/dev/null | jq -r '.results | length'
41
```

Please re-open this ticket.

**Comment by liamg** [comment]
I fixed the original issue by creating a dependency tree for all terraform blocks and evaluating each `for_each`/`count` expansion in the correct order.

I'm guessing this may require a *module-level* dependency tree, which is going to be a little bit more complicated...

**Comment by liamg** [comment]
@BryanStenson-okta Please could you try this with `v1.2.0`? We've reworked the ordering of module loads. There is still more work to do in the area but I'm interested to see if the latest changes help you at all.

**Comment by BryanStenson-okta** [comment]
Using `v1.2.1`, I'm still seeing inconsistent results:

```
$ ./tfsec-darwin-amd64.v1.2.1 -v                              
v1.2.1
$ ./tfsec-darwin-amd64.v1.2.1 -f json | jq '.results | length'
24
$ ./tfsec-darwin-amd64.v1.2.1 -f json | jq '.results | length'
25
$ ./tfsec-darwin-amd64.v1.2.1 -f json | jq '.results | length'
23
$ ./tfsec-darwin-amd64.v1.2.1 -f json | jq '.results | length'
25
```

I'm not 100% sure the directory I tested this on before, but I picked another random one from our codebase, and I'm still seeing inconsistencies.

I haven't had time to reduce this is a "safe-to-share" example in a gist.  Perhaps I'll have more time to provide that next week.

**Comment by alexisschwartz** [comment]
I can confirm we are seeing the same behavior.  Last working version was `0.63.1`. We've tried `1.2.1` and `1.4.2` and we see non-deterministic results for both

```
$ ./tfsec-darwin-arm64-v1.4.2 -f json | jq '.results | length'
17
$ ./tfsec-darwin-arm64-v1.4.2 -f json | jq '.results | length'
15
$ ./tfsec-darwin-arm64-v1.4.2 -f json | jq '.results | length'
17
$ ./tfsec-darwin-arm64-v1.4.2 -f json | jq '.results | length'
14
$ ./tfsec-darwin-arm64-v1.4.2 -f json | jq '.results | length'
17
```

In our codebase they are being pulled in from dependency modules. For example:
```
Result #14 HIGH IAM policy document uses sensitive action 'logs:CreateLogStream' on wildcarded resource 'arn:aws:logs:'
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 .terraform/modules/secure-baseline/modules/cloudtrail-baseline/main.tf Line 43
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   40  │   statement {
   41  │     sid       = "AWSCloudTrailCreateLogStream2014110"
   42  │     actions   = ["logs:CreateLogStream"]
   43  │     resources = ["arn:aws:logs:${var.region}:${var.aws_account_id}:log-group:${aws_cloudwatch_log_group.cloudtrail_events[0].name}:log-stream:*"]
   44  │   }
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
          ID aws-iam-no-policy-wildcards
      Impact Overly permissive policies may grant access to sensitive resources
  Resolution Specify the exact permissions required, and to which resources they should apply instead of using wildcards.

  More Information
  - https://aquasecurity.github.io/tfsec/v1.2.1/checks/aws/iam/no-policy-wildcards/
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

**Comment by liamg** [comment]
`v1.5.0` enforces a consistent order of parsing files, so may impact on this issue, until further examples are found.

**Comment by BryanStenson-okta** [comment]
Sorry, I know I owe you a distilled example.  I haven't had time yet.  But, I wanted to let you know that 1.5.0 doesn't appear to solve the issue:

```
$ ~/Downloads/tfsec-darwin-amd64.v1.5.0 -v                                                             
v1.5.0
$ for n in $(seq 1 10); do ~/Downloads/tfsec-darwin-amd64.v1.5.0 -f json | jq '.results | length'; done
27
27
27
25
27
26
27
26
27
26
```

**Comment by davidmlee-okta** [comment]
I found a distilled example and have pinpointed the issue to legacy id support:

With legacy ID format using this code
```
resource "aws_security_group" "tfsec test" {
  name        = "TFSec Test"
  description = "Allows internal traffic for tfsec testing"
  vpc_id      = module.aws_vpc_info.vpc.id

    #tfsec:ignore:AWS008
  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    description = "tfsec ingress test"
    cidr_blocks = ["0.0.0.0/0"] 
  }
  
  #tfsec:ignore:AWS009
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    description = "tfsec egress test"
    cidr_blocks = ["0.0.0.0/0"] 
  }
}
```


TFSec `v1.8.0` produces this inconsistent result
```
~/o/tfsec-test ➜ for i in {1..10}; do
 tfsec --exclude-downloaded-modules . -f json 2>/dev/null | jq -r '.results | length'
done
1
1
2
2
1
0
0
1
1
1
```


Changing the ignore IDs to new IDs like this
```
resource "aws_security_group" "tfsec test" {
  name        = "TFSec Test"
  description = "Allows internal traffic for tfsec testing"
  vpc_id      = module.aws_vpc_info.vpc.id

  #tfsec:ignore:aws-vpc-no-public-ingress-sgr
  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    description = "tfsec ingress test"
    cidr_blocks = ["0.0.0.0/0"] 
  }
  
  #tfsec:ignore:aws-vpc-no-public-egress-sgr
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    description = "tfsec egress test"
    cidr_blocks = ["0.0.0.0/0"] 
  }
}
```


We get this result
```
~/o/tfsec-test ➜ for i in {1..10}; do
 tfsec --exclude-downloaded-modules . -f json 2>/dev/null | jq -r '.results | length'
done
0
0
0
0
0
0
0
0
0
0
```

**Comment by liamg** [comment]
@davidmlee-okta Awesome find, thank you! I'll look at this shortly :+1:

**Comment by BryanStenson-okta** [comment]
This is awesome news!  Thanks @davidmlee-okta for the excellently simple repro, and @liamg for your tenacity on sticking with my original report.

Very excited for this.

**Comment by liamg** [comment]
Amazing, thanks for the update!
