### ISSUE TITLE
bug: aws-s3-enable-versioning rule needs update

### ISSUE THREAD

**Issue by zfLQ2qx2** [aquasecurity/tfsec#1912]
**Describe the bug**

In the latest AWS terraform provider the versioning parameter of aws_s3_bucket is depreciated and replaced with a separate object.

Looking at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket we see: 

```
S3 Bucket versioning can be configured in either the standalone resource [aws_s3_bucket_versioning](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_versioning) or with the deprecated parameter versioning in the resource aws_s3_bucket. Configuring with both will cause inconsistencies and may overwrite configuration.
```

Looking at https://aquasecurity.github.io/tfsec/v1.28.0/checks/aws/s3/enable-versioning/ we see that tfsec is not aware of this object so gives a false error when versioning is enabled via the peferred method.

Same is true for aws-s3-enable-bucket-logging, aws-s3-enable-bucket-encryption

**Comment by Kishore-abhimanyu** [comment]
Hi @zfLQ2qx2 

I was trying to reproduce this issue. Even I had this issue some time back and seems like the issue has been resolved now in the latest version. Could you please update to the latest version and try to reproduce this issue?

**Comment by kclinden** [comment]
I still get this issue. My module uses the `aws_s3_bucket_versioning` resource instad of the s3 bucket parameter that is deprecated. TFSEC not detecting this.

TFSEC version v1.28.1
AWS Plugin version v.0.18.0

**Comment by Dunedan** [comment]
I'm encountering this as well for `enable-bucket-encryption` with tfsec v1.28.1.

**Comment by holeunlee** [comment]
also encountering it here with v1.28.1

**Comment by nikpivkin** [comment]
Hi @zfLQ2qx2 !

Now Trivy supports the above resources.

/cc @simar7
